language: python
python:
  - "3.6"

# services:
# - mysql

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  # - pip install -e
# command to run tests

before_script:
  # - mysql -u travis --password="" < scripts/travis.sql
  - export FLASK_APP="$TRAVIS_BUILD_DIR/src/backend/meeting_scheduler_flask.py"
  - export FLASK_DEBUG=1
  - python $TRAVIS_BUILD_DIR/src/backend/Models.py


script: 
  - xvfb-run python $TRAVIS_BUILD_DIR/src/frontend/app.py &
  - prospector --strictness veryhigh
  - pytest
  # - bash scripts/post_commit.sh
#  - python content_extract.py
  # - python $TRAVIS_BUILD_DIR/src/backend/Models.py
  # - python $TRAVIS_BUILD_DIR/src/backend/meeting_scheduler_flask.py &
  # - PID=$!
  # - sleep 2
  # - kill $PID
  # - pytest
  # - xvfb-run python $TRAVIS_BUILD_DIR/src/frontend/app.py
  # - python $TRAVIS_BUILD_DIR/src/frontend/app.py
