language: python
python:
  - "3.6"

services:
- mysql

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  # - pip install -e
# command to run tests

before_script:
  - mysql -e 'create database IF NOT EXISTS ase_project_db;' -uroot
  # - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'dbuser'@'localhost';" -uroot

script: 
#  - python content_extract.py
  - pytest