language: python
python:
  - "3.6"

services:
- mysql

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  # - pip install -e
# command to run tests

before_script:
  - mysql -e 'create database IF NOT EXISTS ase_project_db;' -uroot
  - mysql -e "CREATE TABLE IF NOT EXISTS `user_credentials` (`username` varchar(50) DEFAULT NULL,`nameFirst` varchar(50) DEFAULT NULL,`nameLast` varchar(50) DEFAULT NULL,`password` varchar(50) DEFAULT NULL,`email` varchar(150) DEFAULT NULL,`DOB` date DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;"
  # - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'dbuser'@'localhost';" -uroot

script: 
#  - python content_extract.py
  - pytest