language: python
python:
  - "3.6"

services:
- mysql

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  # - pip install -e
# command to run tests

before_script:
  # - mysql -u travis --password="" < scripts/travis.sql


script: 
#  - python content_extract.py
  - python backend/Models.py
  - python backend/meeting_scheduler.py
  - PID=$!
  - sleep 2
  - kill $PID
  - pytest